name: occitours
description: "Aplicación móvil para turismo y viajes - Occitours"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Estado y Gestión
  provider: ^6.0.0
  
  # HTTP y Networking
  dio: ^5.3.0
  http: ^1.2.2
  
  # Serialización y Modelos
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  
  # Navegación
  go_router: ^17.1.0
  
  # Utilidades
  intl: ^0.20.2
  
  # Formularios
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  shared_preferences: ^2.5.4
  file_picker: ^10.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fincas/
    - assets/fincas/las_margaritas/
    - assets/fincas/las_heliconias/
    - assets/fincas/las_palmas/
    - assets/fincas/la_ilusion/
    - assets/rutas/
    - assets/rutas/avistamiento_aves/
    - assets/rutas/bote_paseo_san_nicolas/
    - assets/rutas/city_tours_santa_fe/
    - assets/rutas/city_tours_tierra_frutas/
    - assets/rutas/experiencia_viña_tigre/
    - assets/rutas/paseo_caballo_bosque/
    - assets/rutas/ruta_uva_sopetran/
    - assets/rutas/senderismo_ecologico/
    - assets/rutas/tours_tres_cascadas/
    - assets/rutas/tour_al_puente_occidente/
    - assets/rutas/tour_cata_vinos/
    - assets/rutas/tour_cuatrimotos/
    - assets/rutas/tour_del_chocolate/
